services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postresql/data
        networks:
            auction-network:
                ipv4_address: 172.18.0.1

    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodb-data:/data/db # Persist data in a named volume (mongodb-data)
        networks:
            auction-network:
                ipv4_address: 172.18.0.2

    rabbitMq:
        image: rabbitmq:3-management-alpine
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            auction-network:
                ipv4_address: 172.18.0.3

    auction-svc:
        build:
            context: .
            dockerfile: ./src/AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - ASPNETCORE_URLS=http://+:7777
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - IdentityServiceUrl=http://identity-svc
            - Kestrel__Endpoints__Grpc__Protocols=Http2
            - Kestrel__Endpoints__Grpc__Url=http://+:7777
            - Kestrel__Endpoints__WebApi__Protocols=Http1
            - Kestrel__Endpoints__WebApi__Url=Http://+:80
        ports:
            - "7001:80"
            - "7777:7777"
        depends_on:
            - postgres
            - rabbitMq
        networks:
            auction-network:
                ipv4_address: 172.18.0.4

    search-svc:
        build:
            context: .
            dockerfile: ./src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDBConnection=mongodb://admin:password@mongodb
            - AuctionServiceUrl=http://auction-svc
        ports:
            - "7002:80"
        depends_on:
            - mongodb
            - rabbitMq
        networks:
            auction-network:
                ipv4_address: 172.18.0.5

    identity-svc:
        build: 
            context: .
            dockerfile: ./src/IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
        ports:
            - 5000:80
        depends_on:
            - postgres
        networks:
            auction-network:
                ipv4_address: 172.18.0.6

    gateway-svc:
        build: 
            context: .
            dockerfile: ./src/GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 6001:80
        networks:
            auction-network:
                ipv4_address: 172.18.0.7

    bid-svc:
        build: 
            context: .
            dockerfile: ./src/BiddingService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
            - IdentityServiceUrl=http://identity-svc
            - GrpcAuction=http://auction-svc:7777
        ports:
            - 7003:80
        depends_on:
            - mongodb
            - rabbitMq
        networks:
            auction-network:
                ipv4_address: 172.18.0.7

networks:
    auction-network:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16

volumes:
    mongodb-data: 
    postgres-data:    
    rabbitmq-data:
