services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123456as
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    
        

volumes:
    postgres-data:
    
