services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postresql/data    

    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodb-data:/data/db # Persist data in a named volume (mongodb-data)
        
    rabbitMq:
        image: rabbitmq:3-management-alpine
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        
    auction-svc:
        build:
            context: .
            dockerfile: ./src/AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports:
            - "7001:80"
        depends_on:
            - postgres
            - rabbitMq
           
    search-svc:
        build:
            context: .
            dockerfile: ./src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDBConnection=mongodb://admin:password@localhost:27017
            - AuctionServiceUrl=http://auction-svc
        ports:
            - "7002:80"
        depends_on:
            - mongodb
            - rabbitMq
    identity-svc:
        image: trycatchlearn/identity-svc:latest
        build: 
            context: .
            dockerfile: src/IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
        ports:
            - 5000:80
        depends_on:
            - postgres

    gateway-svc:
        image: trycatchlearn/gateway-svc:latest
        build: 
            context: .
            dockerfile: src/GatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 6001:80


volumes:
    mongodb-data: 
    postgres-data:    
    rabbitmq-data:
